version: "3.8"

services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.26.2
    platform: linux/amd64
    container_name: geoserver
    platform: linux/amd64
    ports:
      - "8000:8080"
    environment:
      - GEOSERVER_DATA_DIR=/var/local/geoserver
      - POSTGIS_HOST=postgis
      - POSTGIS_DB=geodb
      - POSTGIS_USER=geouser
      - POSTGIS_PASSWORD=geopass
    depends_on:
      - postgis
    restart: unless-stopped

  postgis:
    image: postgis/postgis:latest
    container_name: postgis
    platform: linux/amd64
    environment:
      - POSTGRES_DB=geodb
      - POSTGRES_USER=geouser
      - POSTGRES_PASSWORD=geopass
    platform: linux/amd64
    ports:
      - "5433:5432"
    shm_size: '1gb'
    restart: unless-stopped


  backend-stn:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: backend-stn

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    platform: linux/amd64
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - red01

networks:
  red01:
    driver: bridge
