CREATE TABLE IF NOT EXISTS public.ft_street (
    gid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    geom public.geometry(LineString,4326) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ft_street_name ON public.ft_street (name);
CREATE INDEX IF NOT EXISTS idx_ft_street_geom ON public.ft_street USING GIST (geom);
