CREATE TABLE IF NOT EXISTS public.ft_street (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id text,
    segment_ref text,
    street_code text,
    name text NOT NULL,
    street_type text,
    source text,
    locality text,
    department text,
    geom public.geometry(MultiLineString,4326) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ft_street_name ON public.ft_street (name);
CREATE INDEX IF NOT EXISTS idx_ft_street_locality ON public.ft_street (locality);
CREATE INDEX IF NOT EXISTS idx_ft_street_geom ON public.ft_street USING GIST (geom);
